# Generated by Django 4.1 on 2022-09-17 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=100)),
                ('Noticia', models.CharField(max_length=100)),
                ('Informacion', models.CharField(max_length=300)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('Estudiante', models.ManyToManyField(to='home.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudiante', models.CharField(max_length=100)),
                ('comentario', models.CharField(max_length=300)),
                ('publicacion', models.CharField(max_length=200)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('Estudiante', models.ManyToManyField(to='home.estudiante')),
            ],
        ),
    ]
