# Generated by Django 4.1 on 2022-09-17 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_publicaciones_comentarios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentarios',
            old_name='estudiante',
            new_name='nombre',
        ),
    ]
